services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: zrobleno
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin
  configserver:
    image: configserver:0.0.1-SNAPSHOT
    ports:
      - 8888:8888
  discovery:
    image: discovery:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    depends_on:
      - configserver

  gateway:
    image: gateway:0.0.1-SNAPSHOT
    ports:
      - 8111:8222
    depends_on:
      - discovery
      - configserver
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  services:
    image: service:0.0.1-SNAPSHOT
    ports:
      - 8090:8090
    depends_on:
      - discovery
      - configserver
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  orders:
    image: order:0.0.1-SNAPSHOT
    ports:
      - 8091:8091
    depends_on:
      - discovery
      - configserver
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  feedbacks:
    image: feedback:0.0.1-SNAPSHOT
    ports:
      - 8092:8092
    depends_on:
      - discovery
      - configserver
    environment:
      - SPRING_PROFILES_ACTIVE=dev

networks:
  zipkin:
    driver: bridge

volumes:
    postgres_data:
    pgadmin_data:
    keycloak_data: